### ISSUE TITLE
Guzzle 5 vs 6 client creation difference

### ISSUE THREAD

**Issue by markroland** [mpclarkson/freshdesk-php-sdk#10]
First of all, thank you for this code!

I have 2 projects I am including it in, both of which have existing packages with guzzle dependencies. 

In the project with guzzlehttp/guzzle 6.3.0 your code works fine. 

In my project with guzzlehttp/guzzle 5.3.1 I was receiving a "401 unauthorized" error. I fixed this by changing your code in Api.php to `        $this->client = new Client([
                'defaults' => [
                    'auth' => [$apiKey, 'X']
                ]
            ]
        );`

Additionally, I had a hard time catching this error. The exceptions don't seem to be "bubbling up" to get caught.

Thanks again.

**Comment by mpclarkson** [comment]
Thanks for the feedback. If you used version 0.2 of the library it should work fine with Guzzle 5!

**Comment by markroland** [comment]
Ok, great. Thanks for the response.
